minimum_ios_version = '15.0'
# Uncomment this line to define a global platform for your project
# Note: Update "MinimumOSVersion" in AppFrameworkInfo.plist and "IPHONEOS_DEPLOYMENT_TARGET" below to match as well
platform :ios, minimum_ios_version

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generanated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # CUSTOM: Derive Firestore Tags
  require 'yaml'
  pubspec_lock_path = File.expand_path('../../pubspec.lock', __FILE__)
  pubspec_lock = YAML.load_file(pubspec_lock_path)

  # Extract the resolved version of firebase_core from pubspec.lock
  firebase_core_version = pubspec_lock['packages']['firebase_core']['version']
  Pod::UI.puts "Resolved firebase_core version: #{firebase_core_version}"

  # firebase_core_script = File.join(File.dirname(__FILE__), '.symlinks/plugins/firebase_core/ios/firebase_sdk_version.rb')
  firebase_core_dir = File.expand_path("firebase_core-#{firebase_core_version}", File.join(flutter_root, '..', '.pub-cache', 'hosted', 'pub.dev'))
  firebase_core_script = File.join(firebase_core_dir, 'ios', 'firebase_sdk_version.rb')

  Pod::UI.puts "Looking for firebase_sdk_version.rb script at path: #{firebase_core_script}"
  if File.exist?(firebase_core_script)
    require firebase_core_script
    firebase_sdk_version = firebase_sdk_version!
    Pod::UI.puts "Using Firebase SDK version '#{firebase_sdk_version}' defined in 'firebase_core for FirebaseFirestore framework'"
  else
    raise "Error - unable to locate firebase_sdk_version.rb script in firebase_core, and no FirebaseSDKVersion specified"
  end
  # END CUSTOM

  pod 'FirebaseFirestore',
      :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git',
      :tag => "#{firebase_sdk_version}"

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      if Gem::Version.new(minimum_ios_version) > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = minimum_ios_version
      end
    end
  end
end
