# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Generate Flutter app

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: itachi1706/flutter-alpine-android:web
    steps:
      - uses: actions/checkout@v3
      - name: Retrieve Google Service decode it to a file
        env:
          GOOGLE_SVC_DART: ${{ secrets.GOOGLE_SVC_DART }}
        run: echo $GOOGLE_SVC_DART | base64 --decode > lib/firebase_options.dart
      - name: Pre-Setup
        run: |
          export GIT_COMMIT_COUNT=$GITHUB_RUN_ID
          export CI_COMMIT_SHORT_SHA=$GITHUB_SHA
          echo $GIT_COMMIT_COUNT
          chmod +x ./ciscripts/get_version.sh
          ./ciscripts/get_version.sh
        env:
          CI_PIPELINE_IID: 1337
          APP_BUILD_VER: github
          APP_TYPE: Web
      - name: Test
        run: cat lib/firebase_options.dart
      - name: Build Flutter App
        run: flutter build web
          
